apiVersion: v1
kind: Secret
metadata:
  name: mpsweb
type: Opaque
stringData:
  user: <WEBUI-USERNAME>
  password: <WEBUI-PASSWORD>
---
apiVersion: v1
kind: Secret
metadata:
  name: rps
type: Opaque
stringData:
  connectionString: postgresql://<DATABASE-USERNAME>:<DATABASE-PASSWORD>@<DATABASE-SERVER-URL>:5432/rpsdb?sslmode=<SSL-MODE>
---
apiVersion: v1
kind: Secret
metadata:
  name: mps
type: Opaque
stringData:
  connectionString: postgresql://<DATABASE-USERNAME>:<DATABASE-PASSWORD>@<DATABASE-SERVER-URL>:5432/mpsdb?sslmode=<SSL-MODE>
---
apiVersion: v1
kind: Secret
metadata:
  name: mpsrouter
type: Opaque
stringData:
  connectionString: postgresql://<DATABASE-USERNAME>:<DATABASE-PASSWORD>@<DATABASE-SERVER-URL>:5432/mpsdb?sslmode=<SSL-MODE>
---
apiVersion: v1
kind: Secret
metadata:
  name: open-amt-admin-jwt
  labels:
    konghq.com/credential: jwt
type: Opaque
stringData:
  kongCredType: jwt
  key: admin-issuer
  algorithm: HS256
  secret: <YOUR-SECRET>
---
apiVersion: v1
kind: Secret
metadata:
  name: open-amt-admin-acl
  labels:
    konghq.com/credential: acl
type: Opaque
stringData:
  kongCredType: acl
  group: open-amt-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
type: Opaque
stringData:
  vaultKey: <VAULT-ROOT-TOKEN>
---