#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
# Default values for installServersChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  mps: "intel/oact-mps:latest"
  rps: "intel/oact-rps:latest"
  webui: "intel/oact-webui:latest"
  mpsrouter: "intel/oact-mpsrouter:latest"
mps:
  commonName: 
  replicaCount: 1
  logLevel: "silly"
  jwtExpiration: 1440
ui:
  replicaCount: 1
rps:
  replicaCount: 1
  logLevel: "silly"
vault:
  injector:
    annotations:
      kuma.io/sidecar-injection: disabled
  server:
    annotations:
      kuma.io/sidecar-injection: disabled
  ui:
    annotations:
      kuma.io/sidecar-injection: disabled
    enabled: true
    serviceType: "LoadBalancer"
kong:  
  podAnnotations:
      kuma.io/sidecar-injection: enabled
      kuma.io/gateway: enabled
  env:
    UPSTREAM_KEEPALIVE_POOL_SIZE: 0
  proxy:
    annotations:
      service.beta.kubernetes.io/azure-dns-label-name: ""
    stream:
      - containerPort: 4433
        servicePort: 4433
        parameters: []
    http:
      enabled: false
mpsrouter:
  replicaCount: 1
