on:
  push:
    tags:
      - "*"
name: Build and release on push
permissions:
  contents: read
jobs:
  release:
    name: create release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: clone open amt examples repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.ref }}

      - name: Print github workspace
        run: echo $GITHUB_WORKSPACE && pwd && echo ${{ github.workspace }}

      - name: tar zip helm directory
        shell: bash
        run: |
          (cd $GITHUB_WORKSPACE/kubernetes && tar -czvf open-amt-toolkit-helm.tar.gz charts)

      - name: upload helm tarball release artifact
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace}}/kubernetes/open-amt-toolkit-helm.tar.gz
          asset_name: open-amt-toolkit-helm.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: "Open AMT Cloud Toolkit Helm deployment tarball asset"
